[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
auto_detect_solc = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
eth-mainnet = "${ETH_RPC_URL}"

[etherscan]
eth-mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 9 }
